### PR TITLE
FORTRAN -> Fortran

### PR DESCRIPTION
**Pull request by evaleev**

### CODE REVIEW

**Comment by wavefunction91** [comment]
@ajaypanyala Can you merge this?

**Comment by ajaypanyala** [comment]
This branch has conflicts with `upstream` and needs to be resolved before merging. @evaleev Could you please take a look at it?

**Comment by evaleev** [comment]
I resolved merge conflicts ... for CI to pass @wavefunction91 's openblas CI fixes are needed

**Comment by wavefunction91** [comment]
@ajaypanyala this is g2g

**Pull request merged**
